### ISSUE TITLE
IntelliJ 2018.2.1 reports bogus syntax error when configuring remote buildCache (1.0 RC3)

### ISSUE THREAD

**Issue by eriwen** [gradle/kotlin-dsl-samples#1063]
### Expected Behavior
As a build author, I do not want IDEA to highlight syntax errors that aren't actually errors.

I should be able to configure my buildCache thusly:

```gradle
buildCache {
    remote(HttpBuildCache::class) {
        url = uri("http://example.com/cache/")
    }
}
```

### Current Behavior
Gradle behaves correctly, but IDEA reports a syntax error.

![screenshot 2018-08-24 11 06 30](https://user-images.githubusercontent.com/51534/44601423-4ab0d700-a791-11e8-8bd9-e979381dc914.png)

### Context
This is one of the examples from 1.0 RC release notes.

**Comment by bamboo** [comment]
That's most likely due to #1064.
