### ISSUE TITLE
Overload resolution ambiguity on Kotlin Native plugin DSL

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/kotlin-dsl-samples#1138]
After upgrading to Gradle `4.10.2` and applying it to kotlin native subprojects, following error appeared:
```kotlin
e: /home/egorr/data/work/ktlint-gradle/samples/kotlin-native/build.gradle.kts:11:32: Overload resolution ambiguity: 
public open fun component(configureAction: Action<in AbstractKotlinNativeComponent>): KotlinNativeSourceSetImpl defined in org.jetbrains.kotlin.gradle.plugin.experimental.sourcesets.KotlinNativeSourceSetImpl
public open fun component(configureLambda: AbstractKotlinNativeComponent.() -> Unit): KotlinNativeSourceSetImpl defined in org.jetbrains.kotlin.gradle.plugin.experimental.sourcesets.KotlinNativeSourceSetImpl
```
On previous Gradle version `4.9` there was no problems.

### Expected Behavior

This configuration should work as is:
```kotlin
kotlinNativeSourceSets["main"].component {
    // https://github.com/JetBrains/kotlin-native/issues/1807
    if (this is KotlinNativeMainComponent) {
        outputKinds.set(listOf(OutputKind.EXECUTABLE))
        baseName.set("foo")
        extraOpts(listOf("-entry", "org.jlleitschuh.gradle.ktlint.sample.native.main"))
    }
}
```

### Current Behavior

Fixed changing configuration to following:
```kotlin
kotlinNativeSourceSets["main"].component(Action {
    // https://github.com/JetBrains/kotlin-native/issues/1807
    if (this is KotlinNativeMainComponent) {
        outputKinds.set(listOf(OutputKind.EXECUTABLE))
        baseName.set("foo")
        extraOpts(listOf("-entry", "org.jlleitschuh.gradle.ktlint.sample.native.main"))
    }
})
```

### Context

Happens after updarading from Gradle version `4.9.0` to `4.10.2` in kotlin native plugins configuration block: `konan` and `org.jetbrains.kotlin.native`

### Steps to Reproduce (for bugs)

See commit https://github.com/JLLeitschuh/ktlint-gradle/pull/132/commits/c85ce658518b0ae6f999c544c1a2b2ee44accf90

### Your Environment

https://github.com/JLLeitschuh/ktlint-gradle/pull/132 

cc @JLLeitschuh

**Comment by eskatos** [comment]
Thanks for the detailed report @Tapchicoma!

This is due to 4.10 enabling "SAM conversion for Kotlin functions", see the breaking changes section of https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC6 and https://docs.gradle.org/4.10.2/userguide/kotlin_dsl.html#sec:kotlin_compiler_arguments

It seems `KotlinNativeSourceSet` exposes both `Action<T>` and Kotlin lambda taking functions with the same name, which is ambiguous because they now have the same signature to the kotlin compiler.

Gradle plugins should simply expose `Action<T>` taking functions to work nicely in both Kotlin and Groovy build logic (and Java build logic btw).

**Comment by Tapchicoma** [comment]
@eskatos should I this issue in kotlin-native?

**Comment by JLLeitschuh** [comment]
@eskatos Wouldn't it be better if the Kotlin compiler plugin just didn't generate the overload if the overload already existed?

**Comment by eskatos** [comment]
@Tapchicoma, yes please open an upstream kotlin-native issue

**Comment by eskatos** [comment]
New versions of the Kotlin MPP plugin don't suffer from this issue, closing
