### ISSUE TITLE
Review configurability of the org.jetbrains.kotlin.native/multiplatform plugin using the Gradle Kotlin DSL

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl-samples#1169]
See https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md
And https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html

**Comment by gildor** [comment]
Related issue from kotlin-native issue tracker: https://github.com/JetBrains/kotlin-native/issues/1807

**Comment by eskatos** [comment]
Another issue about the `fromPreset` convention on `kotlin.targets` being hard to use

https://youtrack.jetbrains.com/issue/KT-28635

**Comment by eskatos** [comment]
There's also the nested polymorphic containers starting at `kotlin.targets` where things could be easier.

For example, the following Groovy:

```groovy
def binary = kotlin.targets.ios.compilations.test.getBinary('EXECUTABLE', 'DEBUG')
```
https://github.com/JetBrains/kotlin-mpp-example/blob/63709814d9c6e5cf4f88199e5c17bfb66094db45/greeting/build.gradle#L87

can be translated to:
```kotlin
val binary = kotlin.targets["ios"].compilations.getByName<KotlinNativeCompilation>("test").getBinary("EXECUTABLE", "DEBUG")
```

No, showstopper here, but finding the right type isn't trivial.
