### ISSUE TITLE
Any easy way to add dependency in build.gradle.kts?

### ISSUE THREAD

**Issue by Dollyn** [gradle/kotlin-dsl-samples#1389]
If I use build.gradle, i can still use Alt+Insert > generate dependency  to  search artifacts. Or I can search in https://mvnrepository.com, and copy&paste a dependency directly.

![image](https://user-images.githubusercontent.com/184413/65849367-9febee80-e37c-11e9-85e6-82ac522a48dc.png)

But in build.gradle.kts I got nothing. I have to remember the group name, artifact id, and the deam version, or even the magic string like "org.apache.httpcomponents:httpclient:4.5.10"

**Comment by JLLeitschuh** [comment]
I recommend contacting the maintainer of mvnrepository.com at info@mvnrepository.com

We don't maintain that site.

**Comment by Dollyn** [comment]
that is not what i mean.  what i want is some way i can add a dependency quickly, which don't need me to remember the group name and version number in my head.

**Comment by JLLeitschuh** [comment]
I normally copy and paste it from that website and then reformat to match the Koltin DSL API.

**Comment by gabrielfeo** [comment]
The syntax for Buildr contains a compatible dependency notation, but if the maintainer could add tab for KTS, that'd be great.
