### ISSUE TITLE
Unresolved reference: android

### ISSUE THREAD

**Issue by audientlin** [gradle/kotlin-dsl-samples#1393]
```
plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("android.extensions")
//    kotlin("kapt")
}

android {
}
```

my build.gradle.kts like this, but "Unresolved reference: android"

**Comment by eskatos** [comment]
Thanks for the report @audientlin 

Please note that this repository, `gradle/kotlin-dsl-samples` is for Gradle Kotlin DSL *samples* only.
For bug reports or feature requests, please open issues on https://github.com/gradle/gradle/issues
For usage questions, please use the Gradle forums at https://discuss.gradle.org

That being said, the snippet you provided is not enough to understand what problem you are facing. I'm closing this issue, please use the forum for further questions.

**Comment by MalcolmMcFly** [comment]
@audientlin Did you ever solve this issue? I am experiencing the same problem

**Comment by gkaradagan** [comment]
i also have the same problem

**Comment by bcoronel-fusap** [comment]
https://stackoverflow.com/a/60482635/5279996

**Comment by AntoineGagnon** [comment]
The solution in my case was to completely remove the android {} block, do a gradle sync, and then add it back.
