### ISSUE TITLE
plugins{} block must has a id 

### ISSUE THREAD

**Issue by tonycheng93** [gradle/kotlin-dsl-samples#1394]
i want to use the following usage:
`gradle.properties`
```
isRunAlone=false
```
`build.gradle.kts` 
```
val isRunAlone = (project.property("isRunAlone") as String).toBoolean()

if (isRunAlone) {
    plugins {
        id("com.android.application")
        kotlin("android")
        kotlin("android.extensions")
    }
} else {
    plugins {
        id("com.android.library")
        kotlin("android")
        kotlin("android.extensions")
    }
}
```

in groovy like this is ok 
`build.gradle`
```
if (isRunAlone.toBoolean()) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}
```

**Comment by eskatos** [comment]
Hi @tonycheng93 

Please note that this repository, `gradle/kotlin-dsl-samples` is for Gradle Kotlin DSL *samples* only.
For bug reports or feature requests, please open issues on https://github.com/gradle/gradle/issues
For usage questions, please use the Gradle forums at https://discuss.gradle.org

That being said, you can't conditionally request plugins using the `plugins {}` block, it's the same in Groovy or Kotlin build scripts.

You can do the same as in Groovy in a Kotlin script:

```kotlin
val isRunAlone: Boolean by project
if(isRunAlone) {
    apply(plugin = "com.android.application")
} else {
    apply(plugin = "com.android.library")
}
```

Closing as answered, please use the forum for further questions.
