### ISSUE TITLE
infix the DependencyHandler.`implementation` function?

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl-samples#845]
I shift from a groovy `dependencies.gradle` to a `dependencies.gradle.kts` version.
My previous version looks like that:
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.30"
    implementation "org.jetbrains.kotlin:kotlin-reflect:1.2.30"
}
```

The new version looks like that:
```
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.30")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.2.30")
}
```

I had change the `implementation` to "real method" calls. 
Which is not a issue at all.
But for simplifying (moving from groovy to kotlin), wouldn't it be great if you `infix` the auto genarated `fun DependencyHandler.implementation`?
Then most of the people shouldn't change the dependencies block at all...
Or is that nor possible somehow? 🤔

**Comment by gildor** [comment]
you cannot use infix functions in Kotlin like that.
The only what you can do is: 
```
this implementation "my:dependency"
```

This is expected behaviour of Kotlin

**Comment by StefMa** [comment]
Why can't we use infix functions for that?
As far as I remind me correctly, the generated `accessor.kt`  have a extension function like
`fun DependencyHandler.implementation(aName: String) {...}`
Changing it to 
[`infix fun DependencyHandler.implementation(aName: String) {...}`](https://kotlinlang.org/docs/reference/functions.html#infix-notation) 
should be possible, right? 🤔

**Comment by gildor** [comment]
@StefMa  Just try it if you don't believe. 
Kotlin just do not allow to use infix functions like you want, infix function always have 2 arguments and the first argument cannot be implicitly used from `this`

**Comment by StefMa** [comment]
According to [their documentation](https://kotlinlang.org/docs/reference/functions.html#infix-notation) infix should have only 1 argument (parameter)!
> * They must be member functions or extension functions;
> * They must have a single parameter;
> * The parameter must not accept variable number of arguments and must have no default value.

Why should I use `this`? 🤔 
Whatever. I'll try that and report here soon...

**Comment by StefMa** [comment]
Just tried it with that config:
```kotlin
plugins {
  id("org.gradle.java")
}

infix fun DependencyHandler.implementation(int: Int) {
  println("Hello $int")
}
```
What is working:
```kotlin
dependencies {
 implementation("com.google.code.gson:gson:2.8.4")
 this implementation 2
}
```
But this isn't working (you cannot omit `this` :/):
```kotlin
dependencies {
 implementation("com.google.code.gson:gson:2.8.4")
 implementation 2
}
```
See also [this](https://discuss.kotlinlang.org/t/infix-function-in-receivers/6554/5) and [this](https://discuss.kotlinlang.org/t/is-any-way-call-infix-function-without-this-caller/1688/9)...

So it seems it is really not possible to use `infix` like I've expected/wanted here :/
